-- Runs in the migration transaction; all fixtures are removed before commit.
do $test$
declare employee uuid=gen_random_uuid(); administrator uuid; partner uuid; test_id bigint; n bigint; version timestamptz; saved public.customer_enquiries; blocked boolean;
begin
 select user_id into administrator from public.staff_profiles where role='admin' and is_active limit 1;
 if administrator is null then raise exception 'Missing existing admin'; end if;
 select user_id into partner from public.venue_partner_profiles where is_active limit 1;
 insert into auth.users(id,aud,role,email) values(employee,'authenticated','authenticated','smv-test-'||employee||'@example.invalid');
 insert into public.staff_profiles(user_id,full_name,role,is_active) values(employee,'Permission test employee','agent',true);
 insert into public.customer_enquiries(customer_name,mobile,location,occasion,source,updated_at) values('Permission test lead','9999999991','Delhi','Other','Internal permission test',now()-interval '1 second') returning id,updated_at into test_id,version;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee,'role','authenticated')::text,true);
 perform set_config('request.jwt.claim.sub',employee::text,true);
 set local role authenticated;
 if public.smv_is_active_staff() then raise exception 'FAIL employee has admin role'; end if;
 if not public.is_crm_staff() then raise exception 'FAIL employee denied CRM role'; end if;
 select count(*) into n from public.customer_enquiries where id=test_id;
 if n<>1 then raise exception 'FAIL employee read'; end if;
 update public.customer_enquiries set customer_name='Unauthorized' where id=test_id;get diagnostics n=row_count;
 if n<>0 then raise exception 'FAIL direct employee write'; end if;
 delete from public.customer_enquiries where id=test_id;get diagnostics n=row_count;
 if n<>0 then raise exception 'FAIL employee deletion'; end if;
 update public.staff_profiles set role='admin' where user_id=employee;get diagnostics n=row_count;
 if n<>0 then raise exception 'FAIL role escalation'; end if;
 select count(*) into n from public.venues;if n<>0 then raise exception 'FAIL venue access'; end if;
 select * into saved from public.smv_employee_save_lead(test_id,version,'{"call_outcome":"Connected","status":"follow-up","guests":120}'::jsonb,'Customer requested a call tomorrow',true);
 if saved.contact_count<>1 or saved.status<>'follow-up' then raise exception 'FAIL permitted save'; end if;
 select count(*) into n from public.crm_activity_log where lead_id=test_id and created_by=employee;
 if n<>1 then raise exception 'FAIL automatic audit'; end if;
 blocked=false;
 begin perform public.smv_employee_save_lead(test_id,version,'{}'::jsonb,'Stale save',false);exception when serialization_failure then blocked=true;end;
 if not blocked then raise exception 'FAIL stale save accepted'; end if;
 blocked=false;
 begin perform public.smv_employee_save_lead(test_id,saved.updated_at,jsonb_build_object('assigned_to',employee),'',false);exception when insufficient_privilege then blocked=true;end;
 if not blocked then raise exception 'FAIL protected assignment'; end if;
 blocked=false;
 begin insert into public.crm_activity_log(lead_id,activity_type,description,created_by) values(test_id,'employee_update','Forged',employee);exception when insufficient_privilege then blocked=true;end;
 if not blocked then raise exception 'FAIL forged audit'; end if;
 reset role;
 update public.staff_profiles set is_active=false where user_id=employee;
 set local role authenticated;
 select count(*) into n from public.customer_enquiries where id=test_id;if n<>0 then raise exception 'FAIL inactive read'; end if;
 blocked=false;
 begin perform public.smv_employee_save_lead(test_id,saved.updated_at,'{}'::jsonb,'',false);exception when insufficient_privilege then blocked=true;end;
 if not blocked then raise exception 'FAIL inactive save'; end if;
 reset role;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',administrator,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',administrator::text,true);
 set local role authenticated;
 if not public.smv_is_active_staff() then raise exception 'FAIL admin locked out'; end if;
 update public.customer_enquiries set customer_name='Admin test update' where id=test_id;get diagnostics n=row_count;
 if n<>1 then raise exception 'FAIL admin update'; end if;
 select count(*) into n from public.crm_activity_log where lead_id=test_id;if n<>1 then raise exception 'FAIL admin audit visibility'; end if;
 reset role;
 if partner is not null then
  perform set_config('request.jwt.claims',jsonb_build_object('sub',partner,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',partner::text,true);
  set local role authenticated;
  select count(*) into n from public.customer_enquiries where id=test_id;if n<>0 then raise exception 'FAIL partner raw lead access'; end if;
  select count(*) into n from public.crm_activity_log where lead_id=test_id;if n<>0 then raise exception 'FAIL partner CRM log access'; end if;
  reset role;
 end if;
 perform set_config('request.jwt.claims','{"role":"anon"}',true);perform set_config('request.jwt.claim.sub','',true);
 set local role anon;
 select count(*) into n from public.customer_enquiries where id=test_id;if n<>0 then raise exception 'FAIL anonymous read'; end if;
 insert into public.customer_enquiries(customer_name,mobile,location,occasion,source) values('Website permission test','9999999992','Delhi','Other','Permission test website');
 reset role;
 delete from public.customer_enquiries where id=test_id or (source='Permission test website' and customer_name='Website permission test' and mobile='9999999992');
 delete from auth.users where id=employee;
 perform set_config('request.jwt.claims','{}',true);perform set_config('request.jwt.claim.sub','',true);
end $test$;
