-- Select My Venue — Growth & Insights
-- Notifications + Analytics + Plans + controlled public listing
-- Safe to run more than once from the Supabase SQL Editor.

begin;

-- ---------------------------------------------------------------------------
-- 1. Venue plan and website visibility controls
-- ---------------------------------------------------------------------------

alter table public.venues
  add column if not exists public_listing_enabled boolean not null default false,
  add column if not exists partner_plan text not null default 'launch_trial',
  add column if not exists plan_status text not null default 'trialing',
  add column if not exists plan_started_at timestamptz,
  add column if not exists plan_expires_at timestamptz;

create table if not exists public.venue_plans (
  plan_code text primary key,
  plan_name text not null,
  description text,
  display_order integer not null default 0,
  features jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.venue_plans (
  plan_code,
  plan_name,
  description,
  display_order,
  features,
  is_active
)
values
  (
    'launch_trial',
    'Launch Trial',
    'Starter access for approved launch partners.',
    10,
    '["Venue listing","Basic visibility","Enquiries as available","Partner dashboard"]'::jsonb,
    true
  ),
  (
    'partner',
    'Partner',
    'Core listing, enquiry and lead-management access.',
    20,
    '["Venue listing","Assigned enquiries","Partner CRM","Lead tracking","CRM notifications"]'::jsonb,
    true
  ),
  (
    'growth',
    'Growth',
    'Priority visibility and enhanced performance insights.',
    30,
    '["Priority visibility","Advanced analytics","Enhanced promotion","Better lead opportunities"]'::jsonb,
    true
  ),
  (
    'premium',
    'Premium',
    'Featured placement and the complete partner experience.',
    40,
    '["Featured listing","Premium placement","Advanced CRM","Advanced analytics","Enhanced promotion","Priority matching"]'::jsonb,
    true
  )
on conflict (plan_code) do update
set
  plan_name = excluded.plan_name,
  description = excluded.description,
  display_order = excluded.display_order,
  features = excluded.features,
  is_active = excluded.is_active,
  updated_at = now();

alter table public.venue_plans enable row level security;

drop policy if exists smv_authenticated_view_active_plans
on public.venue_plans;

create policy smv_authenticated_view_active_plans
on public.venue_plans
for select
to authenticated
using (is_active = true or public.smv_is_active_staff());

drop policy if exists smv_staff_manage_venue_plans
on public.venue_plans;

create policy smv_staff_manage_venue_plans
on public.venue_plans
for all
to authenticated
using (public.smv_is_active_staff())
with check (public.smv_is_active_staff());

-- ---------------------------------------------------------------------------
-- 2. Reliable Partner CRM notifications
-- ---------------------------------------------------------------------------

create table if not exists public.venue_notifications (
  id bigint generated by default as identity primary key,
  venue_id uuid not null references public.venues(id) on delete cascade,
  user_id uuid,
  assignment_id uuid references public.venue_enquiry_assignments(id) on delete cascade,
  notification_type text not null default 'general',
  title text not null,
  message text,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

alter table public.venue_notifications
  add column if not exists venue_id uuid,
  add column if not exists user_id uuid,
  add column if not exists assignment_id uuid,
  add column if not exists notification_type text,
  add column if not exists title text,
  add column if not exists message text,
  add column if not exists is_read boolean not null default false,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists read_at timestamptz;

create index if not exists venue_notifications_user_created_idx
  on public.venue_notifications (user_id, created_at desc);

create index if not exists venue_notifications_venue_created_idx
  on public.venue_notifications (venue_id, created_at desc);

create index if not exists venue_notifications_assignment_idx
  on public.venue_notifications (assignment_id);

alter table public.venue_notifications enable row level security;

drop policy if exists smv_partner_view_own_notifications
on public.venue_notifications;

create policy smv_partner_view_own_notifications
on public.venue_notifications
for select
to authenticated
using (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.venue_partner_profiles p
    where p.user_id = (select auth.uid())
      and p.venue_id = venue_notifications.venue_id
      and p.is_active = true
  )
);

drop policy if exists smv_staff_manage_notifications
on public.venue_notifications;

create policy smv_staff_manage_notifications
on public.venue_notifications
for all
to authenticated
using (public.smv_is_active_staff())
with check (public.smv_is_active_staff());

create or replace function public.smv_mark_notification_read(
  p_notification_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $function$
declare
  changed_count integer;
begin
  update public.venue_notifications n
  set
    is_read = true,
    read_at = coalesce(n.read_at, now())
  where n.id = p_notification_id
    and n.user_id = (select auth.uid())
    and exists (
      select 1
      from public.venue_partner_profiles p
      where p.user_id = (select auth.uid())
        and p.venue_id = n.venue_id
        and p.is_active = true
    );

  get diagnostics changed_count = row_count;
  return changed_count = 1;
end;
$function$;

create or replace function public.smv_mark_all_notifications_read()
returns integer
language plpgsql
security definer
set search_path = ''
as $function$
declare
  changed_count integer;
begin
  update public.venue_notifications n
  set
    is_read = true,
    read_at = coalesce(n.read_at, now())
  where n.user_id = (select auth.uid())
    and n.is_read = false
    and exists (
      select 1
      from public.venue_partner_profiles p
      where p.user_id = (select auth.uid())
        and p.venue_id = n.venue_id
        and p.is_active = true
    );

  get diagnostics changed_count = row_count;
  return changed_count;
end;
$function$;

revoke all on function public.smv_mark_notification_read(bigint) from public;
revoke all on function public.smv_mark_all_notifications_read() from public;
grant execute on function public.smv_mark_notification_read(bigint) to authenticated;
grant execute on function public.smv_mark_all_notifications_read() to authenticated;

create or replace function public.smv_create_assignment_notification()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  insert into public.venue_notifications (
    venue_id,
    user_id,
    assignment_id,
    notification_type,
    title,
    message,
    is_read
  )
  select
    new.venue_id,
    p.user_id,
    new.id,
    'new_assignment',
    'New enquiry assigned',
    'A new customer enquiry is ready in your Partner CRM.',
    false
  from public.venue_partner_profiles p
  where p.venue_id = new.venue_id
    and p.user_id is not null
    and p.is_active = true
    and not exists (
      select 1
      from public.venue_notifications n
      where n.assignment_id = new.id
        and n.user_id = p.user_id
        and n.notification_type = 'new_assignment'
    );

  return new;
end;
$function$;

drop trigger if exists smv_notify_new_assignment
on public.venue_enquiry_assignments;

create trigger smv_notify_new_assignment
after insert on public.venue_enquiry_assignments
for each row
execute function public.smv_create_assignment_notification();

-- ---------------------------------------------------------------------------
-- 3. Partner and Master CRM analytics RPCs
-- ---------------------------------------------------------------------------

create or replace function public.smv_partner_analytics()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $function$
  with partner_venues as (
    select distinct p.venue_id
    from public.venue_partner_profiles p
    where p.user_id = (select auth.uid())
      and p.is_active = true
  ),
  metrics as (
    select
      count(*)::integer as total,
      count(*) filter (
        where a.assignment_status in ('assigned', 'viewed')
      )::integer as new_leads,
      count(*) filter (
        where a.first_contacted_at is not null
           or a.assignment_status in (
             'contacted', 'detailed_shared', 'follow_up',
             'site_visit', 'negotiation', 'booked', 'converted'
           )
      )::integer as responded,
      count(*) filter (
        where a.assignment_status = 'follow_up'
      )::integer as follow_ups,
      count(*) filter (
        where a.assignment_status = 'site_visit'
      )::integer as site_visits,
      count(*) filter (
        where a.assignment_status = 'negotiation'
      )::integer as negotiations,
      count(*) filter (
        where a.assignment_status in ('booked', 'converted')
      )::integer as bookings,
      count(*) filter (
        where a.assignment_status in ('lost', 'cancelled')
      )::integer as lost,
      round(
        (
          avg(
            extract(epoch from (a.first_contacted_at - a.assigned_at)) / 60.0
          ) filter (
            where a.first_contacted_at is not null
              and a.first_contacted_at >= a.assigned_at
          )
        )::numeric,
        1
      ) as avg_response_minutes
    from public.venue_enquiry_assignments a
    where a.venue_id in (select venue_id from partner_venues)
  )
  select jsonb_build_object(
    'total', m.total,
    'new_leads', m.new_leads,
    'responded', m.responded,
    'follow_ups', m.follow_ups,
    'site_visits', m.site_visits,
    'negotiations', m.negotiations,
    'bookings', m.bookings,
    'lost', m.lost,
    'response_rate', case
      when m.total = 0 then 0
      else round((m.responded::numeric / m.total::numeric) * 100, 1)
    end,
    'conversion_rate', case
      when m.total = 0 then 0
      else round((m.bookings::numeric / m.total::numeric) * 100, 1)
    end,
    'avg_response_minutes', coalesce(m.avg_response_minutes, 0)
  )
  from metrics m;
$function$;

create or replace function public.smv_admin_analytics()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  result jsonb;
begin
  if not coalesce(public.smv_is_active_staff(), false) then
    raise exception 'Staff access required';
  end if;

  with assignment_metrics as (
    select
      count(*)::integer as total_assignments,
      count(*) filter (
        where first_contacted_at is not null
           or assignment_status in (
             'contacted', 'detailed_shared', 'follow_up',
             'site_visit', 'negotiation', 'booked', 'converted'
           )
      )::integer as responded,
      count(*) filter (
        where assignment_status in ('booked', 'converted')
      )::integer as bookings,
      count(*) filter (
        where assignment_status not in ('booked', 'converted', 'lost', 'cancelled')
          and first_contacted_at is null
          and assigned_at < now() - interval '24 hours'
      )::integer as unresponded_24h,
      round(
        (
          avg(
            extract(epoch from (first_contacted_at - assigned_at)) / 60.0
          ) filter (
            where first_contacted_at is not null
              and first_contacted_at >= assigned_at
          )
        )::numeric,
        1
      ) as avg_response_minutes
    from public.venue_enquiry_assignments
  ),
  venue_metrics as (
    select
      count(*)::integer as total_venues,
      count(*) filter (where venue_status = 'approved')::integer as approved,
      count(*) filter (where verification_status = 'verified')::integer as verified,
      count(*) filter (
        where venue_status = 'approved'
          and verification_status = 'verified'
          and public_listing_enabled = true
      )::integer as public_venues
    from public.venues
  ),
  partner_metrics as (
    select count(distinct venue_id)::integer as active_partners
    from public.venue_partner_profiles
    where is_active = true
  )
  select jsonb_build_object(
    'total_venues', v.total_venues,
    'approved_venues', v.approved,
    'verified_venues', v.verified,
    'public_venues', v.public_venues,
    'active_partners', p.active_partners,
    'total_assignments', a.total_assignments,
    'responded', a.responded,
    'bookings', a.bookings,
    'unresponded_24h', a.unresponded_24h,
    'response_rate', case
      when a.total_assignments = 0 then 0
      else round((a.responded::numeric / a.total_assignments::numeric) * 100, 1)
    end,
    'conversion_rate', case
      when a.total_assignments = 0 then 0
      else round((a.bookings::numeric / a.total_assignments::numeric) * 100, 1)
    end,
    'avg_response_minutes', coalesce(a.avg_response_minutes, 0)
  )
  into result
  from assignment_metrics a
  cross join venue_metrics v
  cross join partner_metrics p;

  return result;
end;
$function$;

revoke all on function public.smv_partner_analytics() from public;
revoke all on function public.smv_admin_analytics() from public;
grant execute on function public.smv_partner_analytics() to authenticated;
grant execute on function public.smv_admin_analytics() to authenticated;

-- Public directory remains safe-column-only and now has an explicit website
-- visibility switch independent of approval, verification and CRM assignment.
create or replace function public.smv_public_venues()
returns table (venue jsonb)
language sql
stable
security definer
set search_path = ''
as $function$
  select jsonb_build_object(
    'id', v.id,
    'venue_name', v.venue_name,
    'venue_type', v.venue_type,
    'description', v.description,
    'city', v.city,
    'area', v.area,
    'capacity_min', v.capacity_min,
    'capacity_max', v.capacity_max,
    'price_min_per_person', v.price_min_per_person,
    'price_max_per_person', v.price_max_per_person,
    'food_veg', v.food_veg,
    'food_non_veg', v.food_non_veg,
    'parking_available', v.parking_available,
    'rooms_available', v.rooms_available,
    'google_maps_url', v.google_maps_url,
    'featured', v.featured
  ) as venue
  from public.venues v
  where v.venue_status = 'approved'
    and v.verification_status = 'verified'
    and v.public_listing_enabled = true
  order by v.featured desc, v.venue_name asc;
$function$;

revoke all on function public.smv_public_venues() from public;
grant execute on function public.smv_public_venues() to anon, authenticated;

commit;

-- Read-only verification queries:
-- select plan_code, plan_name, is_active from public.venue_plans order by display_order;
-- select public.smv_admin_analytics();
-- select tgname from pg_trigger where tgname = 'smv_notify_new_assignment';
