'use strict';
(async()=>{
 const {client,el,esc,date,toast}=SMV;let employees=[],resetId=null;
 async function call(body){const {data,error}=await client.functions.invoke('manage-employees',{body});if(error){let detail;try{detail=await error.context.json();}catch{}throw Error(detail?.error||error.message);}if(data?.error)throw Error(data.error);return data;}
 async function load(){try{const data=await call({action:'list'});employees=data.employees||[];el('employeesBody').innerHTML=employees.length?employees.map(e=>`<tr><td>${esc(e.full_name)}</td><td>${esc(e.email)}</td><td><span class="pill ${e.is_active?'good':'bad'}">${e.is_active?'Active':'Inactive'}</span></td><td>${date(e.last_sign_in_at,true)}</td><td><button class="quiet" data-action="${e.is_active?'deactivate':'activate'}" data-user="${esc(e.user_id)}">${e.is_active?'Deactivate':'Activate'}</button> <button class="quiet" data-action="reset_password" data-user="${esc(e.user_id)}">Reset password</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">No employees yet. Create the first account above.</td></tr>';}catch(e){toast(e.message);}}
 async function activity(){const {data,error}=await client.from('crm_activity_log').select('lead_id,description,old_value,new_value,created_at').eq('activity_type','employee_update').order('created_at',{ascending:false}).limit(100);if(error){toast(error.message);return;}el('activityBody').innerHTML=data?.length?data.map(r=>`<tr><td>${date(r.created_at,true)}</td><td>#${r.lead_id}</td><td style="white-space:pre-wrap;max-width:500px">${esc(r.description)}</td><td><details><summary>View changes</summary><div class="history-item"><strong>Before</strong><pre>${esc(r.old_value)}</pre><strong>After</strong><pre>${esc(r.new_value)}</pre></div></details></td></tr>`).join(''):'<tr><td colspan="4" class="empty">Employee lead updates will appear here.</td></tr>';}
 el('createEmployee').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await call({action:'create',full_name:el('employeeName').value,email:el('employeeEmail').value,password:el('employeePassword').value});e.target.reset();toast('Employee account created. Share their login details privately.');await load();}catch(e){toast(e.message);}finally{b.disabled=false;}};
 el('employeesBody').onclick=async e=>{const b=e.target.closest('[data-action]');if(!b)return;const employee=employees.find(x=>x.user_id===b.dataset.user);if(b.dataset.action==='reset_password'){resetId=employee.user_id;el('resetName').textContent=employee.full_name;el('resetForm').reset();el('resetDialog').showModal();return;}if(!confirm(`${b.dataset.action==='deactivate'?'Deactivate':'Activate'} access for ${employee.full_name}?`))return;b.disabled=true;try{await call({action:b.dataset.action,user_id:employee.user_id});toast('Employee access updated');await load();}catch(e){toast(e.message);b.disabled=false;}};
 el('resetForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('[type=submit]');b.disabled=true;try{await call({action:'reset_password',user_id:resetId,password:el('resetPassword').value});el('resetDialog').close();e.target.reset();toast('Password reset. Share the new password privately.');}catch(e){toast(e.message);}finally{b.disabled=false;}};
 el('cancelReset').onclick=()=>el('resetDialog').close();el('refreshEmployees').onclick=load;el('refreshActivity').onclick=activity;
 const {data,error}=await client.rpc('smv_is_active_staff');if(error||data!==true){el('accessMessage').textContent='Administrator sign-in required. Open the master CRM and sign in first.';return;}
 el('accessMessage').hidden=true;el('adminContent').hidden=false;await Promise.all([load(),activity()]);setInterval(()=>{if(!document.hidden)activity();},15000);
})();
